// <auto-generated />
namespace BettingSiteNet.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class SeedCountries : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SeedCountries));
        
        string IMigrationMetadata.Id
        {
            get { return "202205081202016_SeedCountries"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
